//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeJewels.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeJewel
    {
        public int Id { get; set; }
        public string SourceCode { get; set; }
        public string AuthorEmail { get; set; }
        public int Rating { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
